"""Updated model back to older syntax
Revision ID: 0210dda9a8e2
Revises: bba3f8eeebbc
Create Date: 2025-05-04 09:57:23.945123
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0210dda9a8e2'
down_revision = 'bba3f8eeebbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_history', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('total_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('locations_guessed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('correct_guesses',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_history', schema=None) as batch_op:
        batch_op.alter_column('correct_guesses',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('locations_guessed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###