"""Initial migration with explicit constraint names

Revision ID: bba3f8eeebbc
Revises: 
Create Date: 2025-04-29 15:49:16.974049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba3f8eeebbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='fk_friend_friend_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_friend_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('locations_guessed', sa.Integer(), nullable=False),
    sa.Column('correct_guesses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_game_history_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('win_streak', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('win_percentage', sa.Float(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_history_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('actual_latitude', sa.Float(), nullable=False),
    sa.Column('actual_longitude', sa.Float(), nullable=False),
    sa.Column('guessed_latitude', sa.Float(), nullable=False),
    sa.Column('guessed_longitude', sa.Float(), nullable=False),
    sa.Column('distance_error_meters', sa.Float(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_history_id'], ['game_history.id'], name='fk_location_guess_game_history_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_guess')
    op.drop_table('stats')
    op.drop_table('game_history')
    op.drop_table('friend')
    op.drop_table('user')
    # ### end Alembic commands ###