"""empty message

Revision ID: dd82a48fad28
Revises: 0cb70fe7e20d
Create Date: 2025-05-15 12:37:10.368401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd82a48fad28'
down_revision = '0cb70fe7e20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_mimetype', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')
        batch_op.drop_column('profile_picture_mimetype')
        batch_op.drop_column('profile_picture_data')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
